#!/bin/bash
# am-i-root.sh:   Am I root or not?
 
ROOT_UID=0   # Root has $UID 0.
 
if [ "$UID" -eq "$ROOT_UID" ]  # Will the real "root" please stand up?
then
  echo "You are root."
else
  echo "You are just an ordinary user (but mom loves you just the same)."
fi
 
exit 0

# Script per verificare se l'utente che lo sta eseguendo ha i privilegi di root oppure no.
# Viene fatta questa verifica comparando lo user ID (UID) con quello di root (ROOT_UID=0).
# Se l'UID è uguale a 0 l'utente avrà i privilegi di root, se sarà diverso da zero no.
# Con exit 0 si termina l'esecuzione dello script.
 
# ============================================================= #
# Code below will not execute, because the script already exited.
 
# An alternate method of getting to the root of matters:
 
ROOTUSER_NAME=root
 
username=`id -nu`              # Or...   username=`whoami`
if [ "$username" = "$ROOTUSER_NAME" ]
then
  echo "Rooty, toot, toot. You are root."
else
  echo "You are just a regular fella."
fi

# Questo è un metodo alternativo per verificare i privilegi di root confrontando il nome utente anziché l'UID.
