#!/bin/bash
 
# Call this script with at least 10 parameters, for example
# ./scriptname 1 2 3 4 5 6 7 8 9 10
MINPARAMS=10
# Numero minimo di argomenti dello script (in questo caso 10) 
echo
# Riga vuota per leggibilità 
echo "The name of this script is \"$0\"."                # Stampa il nome dello script ($0) e il suo percorso.
# Adds ./ for current directory
echo "The name of this script is \"`basename $0`\"."     # Stampa solo il nome dello script tranne il percorso utilizzando basename.
# Strips out path name info (see 'basename')
 
echo
# Altra riga vuota per leggibilità. 
if [ -n "$1" ]              # Tested variable is quoted.
then
 echo "Parameter #1 is $1"  # Need quotes to escape #
fi
# Verifica se la prima variabile ($1) non è nulla (-n)  e se esiste la stampa. 
if [ -n "$2" ]
then
 echo "Parameter #2 is $2"
fi
# Si ripete questa operazione per ogni variabile fino alla $10. 
if [ -n "$3" ]
then
 echo "Parameter #3 is $3"
fi
 
# ...
 
 
if [ -n "${10}" ]  # Parameters > $9 must be enclosed in {brackets}.
then
 echo "Parameter #10 is ${10}"
fi
 
echo "-----------------------------------"
echo "All the command-line parameters are: "$*""
# Ci mostra tutte le variabili separate da spazi.
if [ $# -lt "$MINPARAMS" ]
then
  echo
  echo "This script needs at least $MINPARAMS command-line arguments!"
fi 
# Controlla se il numero di variabili fornito è minore del numero minimo richiesto (-lt).
# Se risulta vera, stampa il messaggio di errore descritto qua sopra. 
echo
 
exit 0
